FROM ghcr.io/cirruslabs/flutter:3.35.2 AS build

WORKDIR /app
COPY pubspec.yaml pubspec.lock* ./
RUN flutter pub get
COPY . ./
ARG API_BASE_URL
RUN test -n "$API_BASE_URL" && flutter build web --release --dart-define=API_BASE_URL="$API_BASE_URL"

FROM nginx:1.29.1-alpine
COPY nginx.release.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build/web /usr/share/nginx/html
EXPOSE 80
